### ISSUE TITLE
Convert NTriples data into usable JSON-LD

### ISSUE THREAD

**Issue by fsteeg** [hbz/swib18-workshop#2]
For source data see:

https://github.com/hbz/lobid-resources/issues/851
https://github.com/hbz/lobid-resources/pull/919
https://github.com/hbz/lobid-resources/blob/master/src/test/resources/loc_bib_works_test.nt

For implementation see:

https://github.com/hbz/lobid-gnd/blob/master/app/apps/Convert.java#L111

Thoughts:

- Start with playground
- Start without context, without frame, most simple conversion to JSON-LD
- Attempt usage (maybe with jq?), experience problem
- Improve with context, frame

**Comment by acka47** [comment]
I generated the first version of a JSON-LD context. The result was added with 9ed7808dd5221b414c7db5ef91342a9a8f0d34c5.

1. Get the Bibframe vocabulary as Turtle: `$ rapper -i rdfxml -o turtle http://id.loc.gov/ontologies/bibframe.rdf > bibframe20_20180926.ttl`
2. Convert to JSON-LD context with @niklasl's [python script](https://gist.github.com/niklasl/2770154) from 2012 (I could not find a better option by now): `$ python rdf_vocab_to_jsonld_context.py bibframe20_20180926.ttl bibframe > bibframe-context.jsonld`
3. Some manual clean ups (using absolute URIs instead of `bf` prefix etc.)

**Comment by fsteeg** [comment]
Pushed using the context and a simple frame. Open `data/index.html` in a browser for a quick look. See also the README for running the node code (which uses the local context file if you want test local changes). Some things are missing in the context, so far I noticed http://id.loc.gov/ontologies/bflc, http://id.loc.gov/vocabulary/relators, and http://www.w3.org/2000/01/rdf-schema.
